version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose the auth-service on port 5000
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://your_db_user:your_db_password@db:5432/grocerydb  # Internal DB URL
    networks:
      - grocery-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"  # Expose the product-service on port 5003
    environment:
      - PORT=5003
      - DATABASE_URL=postgresql://your_db_user:your_db_password@db:5432/grocerydb  # Internal DB URL
    networks:
      - grocery-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"  # Expose the order-service on port 5002
    environment:
      - PORT=5002
      - DATABASE_URL=postgresql://your_db_user:your_db_password@db:5432/grocerydb  # Internal DB URL
    networks:
      - grocery-network

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env  # Ensure that .env has the necessary credentials
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - grocery-network

networks:
  grocery-network:
    driver: bridge

volumes:
  db-data:
    driver: local
