version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - grocery-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "4000:4000"
    networks:
      - grocery-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "5000:5000"
    networks:
      - grocery-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grocery_db
    networks:
      - grocery-network

networks:
  grocery-network:
    driver: bridge
