services:
  - type: web
    name: grocery-api-gateway
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      cd api-gateway
      npm install express cors http-proxy-middleware
      npm install
    startCommand: |
      cd api-gateway
      node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRODUCT_SERVICE_URL
        value: https://grocery-product-service.onrender.com

  - type: web
    name: grocery-product-service
    env: node
    nodeVersion: 18.17.0
    buildCommand: |
      cd productService
      npm install express cors morgan
      npm install
    startCommand: |
      cd productService
      node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production 