services:
  - type: web
    name: grocery-api-gateway
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PRODUCT_SERVICE_URL
        value: http://localhost:3001

  - type: web
    name: grocery-product-service
    env: node
    nodeVersion: 18.17.0
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 