services:
  - type: web
    name: grocery-api-gateway
    env: node
    nodeVersion: 18.17.0
    rootDir: api-gateway
    buildCommand: cd api-gateway && npm install --production
    startCommand: cd api-gateway && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRODUCT_SERVICE_URL
        value: https://grocery-product-service.onrender.com

  - type: web
    name: grocery-product-service
    env: node
    nodeVersion: 18.17.0
    rootDir: productService
    buildCommand: cd productService && npm install --production
    startCommand: cd productService && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production 