services:
  - type: web
    name: grocery-api-gateway
    env: node
    nodeVersion: 18.17.0
    rootDir: api-gateway
    buildCommand: |
      cd api-gateway
      npm install --engine-strict
      npm install express cors http-proxy-middleware
    startCommand: cd api-gateway && node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PRODUCT_SERVICE_URL
        value: http://localhost:3001

  - type: web
    name: grocery-product-service
    env: node
    nodeVersion: 18.17.0
    rootDir: productService
    buildCommand: |
      cd productService
      npm install --engine-strict
      npm install express cors morgan
    startCommand: cd productService && node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 